#!/bin/bash
# Poner en /usr/local/bin/ y el .service en /etc/systemd/system/
# Los permisos son 744, 644
while :; do
    cd /home/ec2-user
    git clone https://ljpalaciom:u-gz6mo99W9sBjs686Db@gitlab.com/ljpalaciom/credentialsaws.git/
    success=$?
    if [ $success -eq 0 ]; then
        echo "Repository successfully cloned."
        chown ec2-user -R /home/ec2-user/moodle_data
    fi

    cd /home/ec2-user/credentialsaws

    git fetch
    if [ $(git rev-parse HEAD) != $(git rev-parse @{u}) ]; then  # if there is something to pull
        if ! chown ec2-user -R /home/ec2-user/moodle_data; then
            logger "Error al cambiar usuario de la carpeta moodle_data"
        else
            logger "Actualizados los permisos de la carpeta moodle_data"
        fi
    fi

    if ! git pull origin master; then
        logger "Error al actualizar web"
    fi

    if ! docker-compose up -d --build; then
        logger "Error al restablecer el contenedor"
    fi
    sleep 20s
done
